proc ds2;
	package work.pxweb_skapaStmtFraga / overwrite=yes;

		method pxweb_skapaStmtFraga();

		end;
		
		method prepare_s(in_out nvarchar(5000000) iRespons, in_out varchar(32) tmpTable, in_out varchar(1000) sqlinsert, in_out integer d, in_out integer c);
			declare package json j();
			declare package work.pxweb_GemensammaMetoder g_metoder();
			declare varchar(1000) sqlValues valueString;
			declare varchar(250) token code text comment type unit;
			declare integer rc tokenType parseFlags tmpCeller loopNr;

			rc=j.createparser(iRespons);
			sqlInsert='insert into ' || tmpTable || ' ( ';
			sqlValues=' values (';
			loopNr=1;
			d=0;
			c=0;
			do until(trim(token)='columns');
				j.getNextToken(rc,token,tokenType,parseFlags);

			end;
			do until(j.ISRIGHTBRACKET(tokenType));
				type='d'; *Kollar senare om denna behövs;
				do until(j.isrightbrace(tokenType));
					if trim(token)='code' then do;
						j.getNextToken(rc,token,tokenType,parseFlags);
						g_metoder.kollaVariabelNamn(token);
						code=trim(token);
					end;
					else if trim(token)='text' then do;
						j.getNextToken(rc,token,tokenType,parseFlags);
						text=trim(token);
					end;
					else if trim(token)='comment' then do;
						j.getNextToken(rc,token,tokenType,parseFlags);
						comment=trim(token);
					end;
					else if trim(token)='type' then do;
						j.getNextToken(rc,token,tokenType,parseFlags);
						type=trim(token);
					end;
					else if trim(token)='unit' then do;
						j.getNextToken(rc,token,tokenType,parseFlags);
						unit=trim(token);
					end;

					j.getNextToken(rc,token,tokenType,parseFlags);
				end;
				if type='d' then do;
					if loopNr=0 then do;
						sqlInsert=sqlInsert || ', ';
						sqlValues=sqlValues || ', ';
					end;
					else loopNr=0;
					sqlInsert=sqlInsert || code || '_cd' || ', ' || code || '_nm';
					sqlValues=sqlValues || '?, ?';
					d=d+2;
				end;
				if type='t' then do;
					if loopNr=0 then do;
						sqlInsert=sqlInsert || ', ';
						sqlValues=sqlValues || ', ';
					end;
					else loopNr=0;
					sqlInsert=sqlInsert || code || '_cd' || ', ' ||code || '_nm';
					sqlValues=sqlValues || '?, ?';
					if lowCase(text) in ('år', 'kvartal', 'månad') then do;
					*	sqlInsert=sqlInsert || ', ' || code || '_dt';
					*	sqlValues=sqlValues || ', ?';
					end;
					d=d+3;
				end;
				if type='c' then do;
					sqlInsert=sqlInsert || ', ' || code;
					sqlValues=sqlValues || ', ?';
					c=c+1;
				end;
				j.getNextToken(rc,token,tokenType,parseFlags);
			end;
			sqlInsert=sqlInsert || ')' || sqlValues || ')';
		end;*S_prepare end;

endpackage;* pxweb_skapaStmtFraga;
run;quit;